version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=production
      - LIGHTHOUSE_URL=http://host.docker.internal:3002
    extra_hosts:
      - "host.docker.internal:host-gateway"